name: geof2
channels:
    - conda-forge
dependencies:
    - python=2.7
    - pip
    - future
    - numpy
    - scipy
    - matplotlib
    - pillow
    - jupyter
    - seaborn
    - numba
    - basemap
    - pip:
        - fatiando==0.5
